@echo off
echo Staging all project changes...
git add .
echo Committing changes...
git commit -m "Update TRD-LEX: CORS configuration, official Thai terminology, auto-port discovery, full offline fallback, and Vercel updates"
echo Pushing to GitHub repository...
git push
echo Successfully pushed to Git! Vercel will automatically trigger deployment.
